# Generated by Django 2.2.5 on 2019-10-28 22:54

from django.db import migrations
import users.userModel


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191028_2250'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.userModel.UserManager()),
            ],
        ),
    ]
