# Generated by Django 2.2.5 on 2019-10-31 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('authtoken', '0002_auto_20160226_1747'),
        ('users', '0003_auto_20191031_1910'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agent',
            new_name='AgentUser',
        ),
    ]
