# Generated by Django 2.2.5 on 2019-11-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('authtoken', '0002_auto_20160226_1747'),
        ('users', '0004_auto_20191031_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_responsible',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AgentUser',
        ),
    ]
