# Generated by Django 2.2.5 on 2019-10-16 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sensor',
            table='sensor_sensor',
        ),
    ]
