# Generated by Django 2.2.5 on 2019-10-16 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_auto_20191016_0524'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sensor',
            table=None,
        ),
    ]
