# Generated by Django 2.2.5 on 2019-10-16 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_auto_20191016_0525'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
