# Generated by Django 2.2.5 on 2019-10-26 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_delete_measure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkAssignment',
        ),
    ]
