# Generated by Django 2.2.5 on 2019-10-24 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=12)),
                ('description', models.TextField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('tolerance_to_make_a_alert', models.FloatField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='BrightnessSensor',
            fields=[
                ('sensor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='alerts.Sensor')),
            ],
            bases=('alerts.sensor',),
        ),
        migrations.CreateModel(
            name='CarbonDioxideSensor',
            fields=[
                ('sensor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='alerts.Sensor')),
            ],
            bases=('alerts.sensor',),
        ),
        migrations.CreateModel(
            name='HumiditySensor',
            fields=[
                ('sensor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='alerts.Sensor')),
            ],
            bases=('alerts.sensor',),
        ),
        migrations.CreateModel(
            name='MosquitoSensor',
            fields=[
                ('sensor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='alerts.Sensor')),
                ('mosquito_sensor_frequency', models.CharField(choices=[('M', 'Minute'), ('H', 'Hour'), ('D', 'Day')], default='D', max_length=1)),
            ],
            bases=('alerts.sensor',),
        ),
    ]
