# Generated by Django 2.2.5 on 2019-11-04 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='geocode_destin',
        ),
        migrations.RemoveField(
            model_name='report',
            name='geocode_origin',
        ),
    ]
