# Generated by Django 2.2.5 on 2019-11-04 03:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_auto_20191104_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='geocode_destin',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='geocode_origin',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
