# Generated by Django 2.2.5 on 2019-10-29 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='CentralEntity',
            fields=[
                ('institution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='institutions.Institution')),
            ],
            bases=('institutions.institution',),
        ),
        migrations.CreateModel(
            name='ControlCenter',
            fields=[
                ('institution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='institutions.Institution')),
            ],
            bases=('institutions.institution',),
        ),
        migrations.CreateModel(
            name='PublicEntity',
            fields=[
                ('institution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='institutions.Institution')),
            ],
            bases=('institutions.institution',),
        ),
    ]
