# Generated by Django 2.2.5 on 2019-10-22 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_institution_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConrolCenter',
            new_name='ControlCenter',
        ),
    ]
